sudo: required
addons:
  chrome: stable

language: node_js
node_js:
- "10"

branches:
  only:
  - master
  - /^greenkeeper/.*$/

before_script:
- npm install -g @angular/cli
- npm install typescript@'>=2.7.2 <2.8'
- npm install

script:
- ng build
