sudo: required
addons:
  chrome: stable

language: node_js
node_js:
- "10"

branches:
  only:
  - master

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

before_script:
- npm install -g @angular/cli
- npm install typescript@'>=2.7.2 <2.8'
- npm install



script:
- npm build
- npm test

after_script:
- cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
